### ISSUE TITLE
ATE in CLAN plots

### ISSUE THREAD

**Issue by mgalashin** [mwelz/GenericML#13]
Hi!

The plot method is adding the ATE mean and error bars for the CLAN plots. It doesn't make much sense, since the ATE is unrelated to the CLANs (even the scale is different).
It looks like it is easily fixable either by removing the layer for the plot or changing it to the average of the CLAN covariate.
Btw, thank you for the great package!

Best,
Misha

**Comment by mwelz** [comment]
Dear @mgalashin,

Thank you for your interest in our package and sorry for the late reply (teaching obligations and easter holidays have kept me busy). I agree that having the ATE in a plot of the CLANs can sometimes be confusing, so including the ATE in the plot should at least be optional. Hence, I have added the argument `plot_ATE` to `plot.GenericML()` in PR #14 (you can download the development version via `devtools::install_github("mwelz/GenericML")`) . If you set this argument to `FALSE`, then neither the ATE nor its confidence bounds will be added to the plot.

I hope this helps!

All the best,
Max

**Comment by aalfons** [comment]
@mwelz, I don't think that `plot_ATE` is a good name for the argument. Plotting is what the function does, so including `plot_` in the argument name is redundant and requires the user to type more than necessary. Why not just call the argument `ATE`? It's short and clean.

**Comment by mwelz** [comment]
@aalfons Fully agreed and fixed in #15.

**Comment by mgalashin** [comment]
Thank you, @mwelz and @aalfons!
